// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

/*
Package gogo is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	TestRequest
	TestResponse
	CustomOption
*/
package gogo

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TestRequest struct {
	Foo string `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar string `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{0} }

func (m *TestRequest) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *TestRequest) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

type TestResponse struct {
	Foo   string        `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar   string        `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	Sopt1 bool          `protobuf:"varint,3,opt,name=sopt1,proto3" json:"sopt1,omitempty"`
	Mopt1 bool          `protobuf:"varint,4,opt,name=mopt1,proto3" json:"mopt1,omitempty"`
	Mopt2 *CustomOption `protobuf:"bytes,5,opt,name=mopt2" json:"mopt2,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{1} }

func (m *TestResponse) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *TestResponse) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

func (m *TestResponse) GetSopt1() bool {
	if m != nil {
		return m.Sopt1
	}
	return false
}

func (m *TestResponse) GetMopt1() bool {
	if m != nil {
		return m.Mopt1
	}
	return false
}

func (m *TestResponse) GetMopt2() *CustomOption {
	if m != nil {
		return m.Mopt2
	}
	return nil
}

type CustomOption struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *CustomOption) Reset()                    { *m = CustomOption{} }
func (m *CustomOption) String() string            { return proto.CompactTextString(m) }
func (*CustomOption) ProtoMessage()               {}
func (*CustomOption) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{2} }

func (m *CustomOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomOption) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

var E_Mopt1 = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50059,
	Name:          "test.mopt1",
	Tag:           "varint,50059,opt,name=mopt1",
	Filename:      "test.proto",
}

var E_Mopt2 = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*CustomOption)(nil),
	Field:         50060,
	Name:          "test.mopt2",
	Tag:           "bytes,50060,opt,name=mopt2",
	Filename:      "test.proto",
}

var E_Sopt1 = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50061,
	Name:          "test.sopt1",
	Tag:           "varint,50061,opt,name=sopt1",
	Filename:      "test.proto",
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "test.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "test.TestResponse")
	proto.RegisterType((*CustomOption)(nil), "test.CustomOption")
	proto.RegisterExtension(E_Mopt1)
	proto.RegisterExtension(E_Mopt2)
	proto.RegisterExtension(E_Sopt1)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TestService service

type TestServiceClient interface {
	Simple(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Simple(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := grpc.Invoke(ctx, "/test.TestService/Simple", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestService service

type TestServiceServer interface {
	Simple(context.Context, *TestRequest) (*TestResponse, error)
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.TestService/Simple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Simple(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _TestService_Simple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptorTest) }

var fileDescriptorTest = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xc9, 0xbf, 0x69, 0xff, 0xba, 0xed, 0xa1, 0xae, 0x1e, 0x96, 0x1e, 0x34, 0xe4, 0x14,
	0x84, 0x26, 0x34, 0x05, 0x2b, 0x3d, 0xaa, 0x27, 0x41, 0x84, 0xd4, 0x8b, 0xde, 0x92, 0x74, 0x9b,
	0x06, 0x9b, 0xcc, 0xba, 0xbb, 0xe9, 0x2b, 0x54, 0x50, 0xdf, 0xa7, 0x8f, 0xe2, 0xd9, 0x93, 0x8f,
	0x21, 0xbb, 0x9b, 0x42, 0x40, 0x50, 0x6f, 0x33, 0xbf, 0xec, 0x37, 0x33, 0xdf, 0x17, 0x84, 0x24,
	0x15, 0xd2, 0x67, 0x1c, 0x24, 0x60, 0x5b, 0xd5, 0x03, 0x27, 0x03, 0xc8, 0x56, 0x34, 0xd0, 0x2c,
	0xa9, 0x16, 0xc1, 0x9c, 0x8a, 0x94, 0xe7, 0x4c, 0x02, 0x37, 0xef, 0xdc, 0x11, 0xea, 0xde, 0x51,
	0x21, 0x23, 0xfa, 0x54, 0x51, 0x21, 0x71, 0x1f, 0xb5, 0x16, 0x00, 0xc4, 0x72, 0x2c, 0x6f, 0x3f,
	0x52, 0xa5, 0x22, 0x49, 0xcc, 0xc9, 0x3f, 0x43, 0x92, 0x98, 0xbb, 0xcf, 0x16, 0xea, 0x19, 0x8d,
	0x60, 0x50, 0x0a, 0xfa, 0x17, 0x11, 0x3e, 0x42, 0x6d, 0x01, 0x4c, 0x8e, 0x48, 0xcb, 0xb1, 0xbc,
	0xbd, 0xc8, 0x34, 0x8a, 0x16, 0x9a, 0xda, 0x86, 0xea, 0x06, 0x7b, 0x86, 0x86, 0xa4, 0xed, 0x58,
	0x5e, 0x37, 0xc4, 0xbe, 0xf6, 0x75, 0x59, 0x09, 0x09, 0xc5, 0x2d, 0x93, 0x39, 0x94, 0xe6, 0x65,
	0xe8, 0x9e, 0xa3, 0x5e, 0x13, 0x63, 0x8c, 0xec, 0x32, 0x2e, 0x68, 0x7d, 0x8a, 0xae, 0xd5, 0x8e,
	0x75, 0xbc, 0xaa, 0xa8, 0xbe, 0xa6, 0x1d, 0x99, 0x26, 0xbc, 0x37, 0xbe, 0x67, 0x94, 0xaf, 0xf3,
	0x94, 0xe2, 0x2b, 0xd4, 0x99, 0xe5, 0x05, 0x5b, 0x51, 0x7c, 0x60, 0xb6, 0x35, 0x42, 0x19, 0xe0,
	0x26, 0x32, 0x9e, 0xdd, 0xc3, 0xf7, 0x2d, 0xb1, 0x3e, 0xb6, 0xa4, 0x8b, 0xfe, 0xab, 0x8f, 0xa3,
	0x70, 0xdc, 0x9f, 0x0c, 0xec, 0xcf, 0x2d, 0xb1, 0xa6, 0x67, 0xb5, 0x29, 0x7c, 0xec, 0x9b, 0xf8,
	0xfd, 0x5d, 0xfc, 0xfe, 0x0d, 0x95, 0x4b, 0x98, 0x9b, 0x63, 0x05, 0x79, 0xd9, 0xb4, 0x1a, 0xb6,
	0xa7, 0xd7, 0xb5, 0xed, 0x5f, 0x75, 0xaf, 0x5a, 0xf7, 0x53, 0x30, 0xd3, 0x49, 0x1d, 0x37, 0x3e,
	0xf9, 0x36, 0xab, 0xb6, 0xbc, 0x1b, 0xf6, 0xb6, 0x69, 0xfe, 0x91, 0x8b, 0xd3, 0x07, 0x2f, 0xcb,
	0xe5, 0xb2, 0x4a, 0xfc, 0x14, 0x8a, 0x80, 0xf1, 0x58, 0xd0, 0xc7, 0x20, 0x83, 0x61, 0xc6, 0x59,
	0x3a, 0xcc, 0xcb, 0x05, 0x04, 0x6a, 0x67, 0x90, 0x41, 0x06, 0x49, 0x47, 0xcf, 0x1c, 0x7f, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0x96, 0x5e, 0x0e, 0x78, 0x02, 0x00, 0x00,
}
